export const ADD_COMMENT                     = 'ADD_COMMENT';
export const FETCH_COMMENTS                  = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_FULFILLED        = 'FETCH_COMMENTS_FULFILLED';
export const FETCH_COMMENTS_REJECTED         = 'FETCH_COMMENTS_REJECTED';
export const FETCH_CURRENT_COMMENT           = 'FETCH_COMMENT';
export const FETCH_CURRENT_COMMENT_FULFILLED = 'FETCH_COMMENT_FULFILLED';
export const FETCH_CURRENT_COMMENT_REJECTED  = 'FETCH_COMMENT_REJECTED';
